import { Food } from "@/types";

export const FOODS: Food[] = [
  // ─── Breads & Grains ─────────────────────────────────────────────────────
  {
    id: "chapati",
    name: "Chapati / Roti",
    emoji: "🫓",
    calories: 90,
    protein: 3,
    carbs: 15,
    fat: 2,
    servingSize: 1,
    servingUnit: "roti",
    category: "Carbs",
  },
  {
    id: "basmati-rice",
    name: "Basmati Rice",
    emoji: "🍚",
    calories: 210,
    protein: 4,
    carbs: 46,
    fat: 0.4,
    servingSize: 1,
    servingUnit: "cup cooked",
    category: "Carbs",
  },
  {
    id: "naan",
    name: "Naan",
    emoji: "🫓",
    calories: 260,
    protein: 9,
    carbs: 45,
    fat: 5,
    servingSize: 1,
    servingUnit: "piece",
    category: "Carbs",
  },
  {
    id: "paratha",
    name: "Plain Paratha",
    emoji: "🫓",
    calories: 180,
    protein: 4,
    carbs: 25,
    fat: 7,
    servingSize: 1,
    servingUnit: "paratha",
    category: "Carbs",
  },
  {
    id: "poha",
    name: "Poha",
    emoji: "🍽️",
    calories: 180,
    protein: 3,
    carbs: 34,
    fat: 4,
    servingSize: 1,
    servingUnit: "cup",
    category: "Carbs",
  },
  {
    id: "idli",
    name: "Idli",
    emoji: "🍽️",
    calories: 130,
    protein: 4,
    carbs: 26,
    fat: 1,
    servingSize: 2,
    servingUnit: "idlis",
    category: "Carbs",
  },
  {
    id: "dosa",
    name: "Plain Dosa",
    emoji: "🥞",
    calories: 120,
    protein: 3,
    carbs: 20,
    fat: 3,
    servingSize: 1,
    servingUnit: "dosa",
    category: "Carbs",
  },
  {
    id: "upma",
    name: "Upma",
    emoji: "🍽️",
    calories: 200,
    protein: 5,
    carbs: 30,
    fat: 7,
    servingSize: 1,
    servingUnit: "cup",
    category: "Carbs",
  },
  // ─── Dal & Legumes ────────────────────────────────────────────────────────
  {
    id: "dal-tadka",
    name: "Dal Tadka",
    emoji: "🫘",
    calories: 180,
    protein: 12,
    carbs: 25,
    fat: 5,
    servingSize: 1,
    servingUnit: "cup",
    category: "Protein",
  },
  {
    id: "chana-dal",
    name: "Chana Dal",
    emoji: "🫘",
    calories: 285,
    protein: 17,
    carbs: 47,
    fat: 2,
    servingSize: 1,
    servingUnit: "cup cooked",
    category: "Protein",
  },
  {
    id: "rajma",
    name: "Rajma",
    emoji: "🫘",
    calories: 225,
    protein: 15,
    carbs: 40,
    fat: 1,
    servingSize: 1,
    servingUnit: "cup cooked",
    category: "Protein",
  },
  {
    id: "chole",
    name: "Chole (Chana Masala)",
    emoji: "🫘",
    calories: 270,
    protein: 14,
    carbs: 42,
    fat: 6,
    servingSize: 1,
    servingUnit: "cup",
    category: "Protein",
  },
  // ─── Vegetables / Sabzi ───────────────────────────────────────────────────
  {
    id: "aloo-gobi",
    name: "Aloo Gobi",
    emoji: "🥦",
    calories: 150,
    protein: 4,
    carbs: 20,
    fat: 7,
    servingSize: 1,
    servingUnit: "cup",
    category: "Vegetables",
  },
  {
    id: "palak-paneer",
    name: "Palak Paneer",
    emoji: "🥬",
    calories: 280,
    protein: 14,
    carbs: 12,
    fat: 20,
    servingSize: 1,
    servingUnit: "cup",
    category: "Vegetables",
  },
  {
    id: "bhindi-masala",
    name: "Bhindi Masala",
    emoji: "🫑",
    calories: 120,
    protein: 3,
    carbs: 12,
    fat: 7,
    servingSize: 1,
    servingUnit: "cup",
    category: "Vegetables",
  },
  {
    id: "baingan-bharta",
    name: "Baingan Bharta",
    emoji: "🍆",
    calories: 130,
    protein: 3,
    carbs: 16,
    fat: 7,
    servingSize: 1,
    servingUnit: "cup",
    category: "Vegetables",
  },
  {
    id: "matar-paneer",
    name: "Matar Paneer",
    emoji: "🫛",
    calories: 250,
    protein: 12,
    carbs: 18,
    fat: 15,
    servingSize: 1,
    servingUnit: "cup",
    category: "Vegetables",
  },
  {
    id: "aloo-matar",
    name: "Aloo Matar",
    emoji: "🥔",
    calories: 175,
    protein: 5,
    carbs: 28,
    fat: 6,
    servingSize: 1,
    servingUnit: "cup",
    category: "Vegetables",
  },
  // ─── Non-Veg ──────────────────────────────────────────────────────────────
  {
    id: "chicken-curry",
    name: "Chicken Curry",
    emoji: "🍗",
    calories: 300,
    protein: 28,
    carbs: 8,
    fat: 18,
    servingSize: 1,
    servingUnit: "cup",
    category: "Protein",
  },
  {
    id: "chicken-tikka",
    name: "Chicken Tikka",
    emoji: "🍗",
    calories: 165,
    protein: 25,
    carbs: 4,
    fat: 6,
    servingSize: 100,
    servingUnit: "g",
    category: "Protein",
  },
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    emoji: "🍗",
    calories: 350,
    protein: 28,
    carbs: 14,
    fat: 20,
    servingSize: 1,
    servingUnit: "cup",
    category: "Protein",
  },
  {
    id: "egg-bhurji",
    name: "Egg Bhurji",
    emoji: "🥚",
    calories: 180,
    protein: 12,
    carbs: 5,
    fat: 13,
    servingSize: 1,
    servingUnit: "serving (2 eggs)",
    category: "Protein",
  },
  {
    id: "fish-curry",
    name: "Fish Curry",
    emoji: "🐟",
    calories: 250,
    protein: 24,
    carbs: 8,
    fat: 14,
    servingSize: 1,
    servingUnit: "cup",
    category: "Protein",
  },
  {
    id: "mutton-curry",
    name: "Mutton Curry",
    emoji: "🥩",
    calories: 370,
    protein: 30,
    carbs: 8,
    fat: 25,
    servingSize: 1,
    servingUnit: "cup",
    category: "Protein",
  },
  // ─── Dairy ────────────────────────────────────────────────────────────────
  {
    id: "paneer",
    name: "Paneer",
    emoji: "🧀",
    calories: 265,
    protein: 18,
    carbs: 3,
    fat: 21,
    servingSize: 100,
    servingUnit: "g",
    category: "Dairy",
  },
  {
    id: "dahi",
    name: "Dahi (Curd)",
    emoji: "🫙",
    calories: 150,
    protein: 8,
    carbs: 12,
    fat: 8,
    servingSize: 1,
    servingUnit: "cup",
    category: "Dairy",
  },
  {
    id: "lassi",
    name: "Lassi (Sweet)",
    emoji: "🥛",
    calories: 180,
    protein: 7,
    carbs: 28,
    fat: 5,
    servingSize: 1,
    servingUnit: "glass (250ml)",
    category: "Dairy",
  },
  {
    id: "chaas",
    name: "Chaas (Buttermilk)",
    emoji: "🥛",
    calories: 60,
    protein: 3,
    carbs: 8,
    fat: 2,
    servingSize: 1,
    servingUnit: "glass (250ml)",
    category: "Dairy",
  },
  {
    id: "ghee",
    name: "Ghee",
    emoji: "🫙",
    calories: 45,
    protein: 0,
    carbs: 0,
    fat: 5,
    servingSize: 1,
    servingUnit: "tsp",
    category: "Fats",
  },
  // ─── Rice Dishes ──────────────────────────────────────────────────────────
  {
    id: "biryani",
    name: "Biryani",
    emoji: "🍛",
    calories: 350,
    protein: 18,
    carbs: 45,
    fat: 10,
    servingSize: 1,
    servingUnit: "cup",
    category: "Carbs",
  },
  {
    id: "veg-pulao",
    name: "Veg Pulao",
    emoji: "🍛",
    calories: 250,
    protein: 6,
    carbs: 42,
    fat: 7,
    servingSize: 1,
    servingUnit: "cup",
    category: "Carbs",
  },
  {
    id: "khichdi",
    name: "Khichdi",
    emoji: "🍛",
    calories: 200,
    protein: 8,
    carbs: 35,
    fat: 3,
    servingSize: 1,
    servingUnit: "cup",
    category: "Carbs",
  },
  {
    id: "pongal",
    name: "Pongal",
    emoji: "🍛",
    calories: 220,
    protein: 7,
    carbs: 38,
    fat: 6,
    servingSize: 1,
    servingUnit: "cup",
    category: "Carbs",
  },
  // ─── South Indian ─────────────────────────────────────────────────────────
  {
    id: "uttapam",
    name: "Uttapam",
    emoji: "🥞",
    calories: 160,
    protein: 5,
    carbs: 25,
    fat: 5,
    servingSize: 1,
    servingUnit: "piece",
    category: "Carbs",
  },
  {
    id: "medu-vada",
    name: "Medu Vada",
    emoji: "🍩",
    calories: 190,
    protein: 7,
    carbs: 24,
    fat: 9,
    servingSize: 2,
    servingUnit: "vadas",
    category: "Snacks",
  },
  {
    id: "sambar",
    name: "Sambar",
    emoji: "🍲",
    calories: 120,
    protein: 6,
    carbs: 18,
    fat: 3,
    servingSize: 1,
    servingUnit: "cup",
    category: "Protein",
  },
  // ─── Snacks ───────────────────────────────────────────────────────────────
  {
    id: "samosa",
    name: "Samosa",
    emoji: "🥟",
    calories: 260,
    protein: 4,
    carbs: 30,
    fat: 14,
    servingSize: 1,
    servingUnit: "piece",
    category: "Snacks",
  },
  {
    id: "pakora",
    name: "Pakora",
    emoji: "🍤",
    calories: 200,
    protein: 5,
    carbs: 22,
    fat: 10,
    servingSize: 4,
    servingUnit: "pieces",
    category: "Snacks",
  },
  {
    id: "bhel-puri",
    name: "Bhel Puri",
    emoji: "🍿",
    calories: 180,
    protein: 5,
    carbs: 30,
    fat: 5,
    servingSize: 1,
    servingUnit: "cup",
    category: "Snacks",
  },
  {
    id: "vada-pav",
    name: "Vada Pav",
    emoji: "🫔",
    calories: 300,
    protein: 7,
    carbs: 42,
    fat: 12,
    servingSize: 1,
    servingUnit: "piece",
    category: "Snacks",
  },
  {
    id: "dhokla",
    name: "Dhokla",
    emoji: "🟡",
    calories: 100,
    protein: 5,
    carbs: 16,
    fat: 2,
    servingSize: 2,
    servingUnit: "pieces",
    category: "Snacks",
  },
  {
    id: "sabudana-khichdi",
    name: "Sabudana Khichdi",
    emoji: "🍽️",
    calories: 320,
    protein: 4,
    carbs: 60,
    fat: 8,
    servingSize: 1,
    servingUnit: "cup",
    category: "Carbs",
  },
  {
    id: "pani-puri",
    name: "Pani Puri",
    emoji: "🫧",
    calories: 200,
    protein: 4,
    carbs: 32,
    fat: 7,
    servingSize: 6,
    servingUnit: "pieces",
    category: "Snacks",
  },
  // ─── Fruits ───────────────────────────────────────────────────────────────
  {
    id: "mango",
    name: "Mango",
    emoji: "🥭",
    calories: 150,
    protein: 2,
    carbs: 35,
    fat: 1,
    servingSize: 1,
    servingUnit: "medium",
    category: "Fruit",
  },
  {
    id: "banana",
    name: "Banana",
    emoji: "🍌",
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.4,
    servingSize: 1,
    servingUnit: "medium",
    category: "Fruit",
  },
  {
    id: "guava",
    name: "Guava",
    emoji: "🍈",
    calories: 68,
    protein: 2.6,
    carbs: 14,
    fat: 1,
    servingSize: 1,
    servingUnit: "medium",
    category: "Fruit",
  },
  {
    id: "papaya",
    name: "Papaya",
    emoji: "🍑",
    calories: 55,
    protein: 0.9,
    carbs: 14,
    fat: 0.2,
    servingSize: 1,
    servingUnit: "cup",
    category: "Fruit",
  },
  // ─── Sweets ───────────────────────────────────────────────────────────────
  {
    id: "kheer",
    name: "Kheer",
    emoji: "🍮",
    calories: 280,
    protein: 8,
    carbs: 45,
    fat: 8,
    servingSize: 1,
    servingUnit: "cup",
    category: "Sweets",
  },
  {
    id: "ladoo",
    name: "Besan Ladoo",
    emoji: "🟠",
    calories: 190,
    protein: 4,
    carbs: 28,
    fat: 8,
    servingSize: 1,
    servingUnit: "piece",
    category: "Sweets",
  },
  {
    id: "gajar-halwa",
    name: "Gajar Halwa",
    emoji: "🥕",
    calories: 300,
    protein: 5,
    carbs: 45,
    fat: 12,
    servingSize: 1,
    servingUnit: "cup",
    category: "Sweets",
  },
];
