import { Food } from "@/types";

export const FOODS: Food[] = [
  {
    id: "chicken-breast",
    name: "Chicken Breast",
    emoji: "🍗",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    servingSize: 100,
    servingUnit: "g",
    category: "Protein",
  },
  {
    id: "brown-rice",
    name: "Brown Rice",
    emoji: "🍚",
    calories: 216,
    protein: 5,
    carbs: 45,
    fat: 1.8,
    servingSize: 1,
    servingUnit: "cup",
    category: "Carbs",
  },
  {
    id: "egg",
    name: "Egg",
    emoji: "🥚",
    calories: 72,
    protein: 6,
    carbs: 0.4,
    fat: 5,
    servingSize: 1,
    servingUnit: "egg",
    category: "Protein",
  },
  {
    id: "banana",
    name: "Banana",
    emoji: "🍌",
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.4,
    servingSize: 1,
    servingUnit: "medium",
    category: "Fruit",
  },
  {
    id: "oatmeal",
    name: "Oatmeal",
    emoji: "🥣",
    calories: 150,
    protein: 5,
    carbs: 27,
    fat: 3,
    servingSize: 1,
    servingUnit: "cup",
    category: "Carbs",
  },
  {
    id: "greek-yogurt",
    name: "Greek Yogurt",
    emoji: "🫙",
    calories: 100,
    protein: 17,
    carbs: 6,
    fat: 0.7,
    servingSize: 170,
    servingUnit: "g",
    category: "Dairy",
  },
  {
    id: "almonds",
    name: "Almonds",
    emoji: "🌰",
    calories: 164,
    protein: 6,
    carbs: 6,
    fat: 14,
    servingSize: 28,
    servingUnit: "g",
    category: "Nuts",
  },
  {
    id: "salmon",
    name: "Salmon",
    emoji: "🐟",
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    servingSize: 100,
    servingUnit: "g",
    category: "Protein",
  },
  {
    id: "sweet-potato",
    name: "Sweet Potato",
    emoji: "🍠",
    calories: 103,
    protein: 2.3,
    carbs: 24,
    fat: 0.1,
    servingSize: 1,
    servingUnit: "medium",
    category: "Carbs",
  },
  {
    id: "broccoli",
    name: "Broccoli",
    emoji: "🥦",
    calories: 55,
    protein: 3.7,
    carbs: 11,
    fat: 0.6,
    servingSize: 1,
    servingUnit: "cup",
    category: "Vegetables",
  },
  {
    id: "white-rice",
    name: "White Rice",
    emoji: "🍚",
    calories: 200,
    protein: 4,
    carbs: 44,
    fat: 0.4,
    servingSize: 1,
    servingUnit: "cup",
    category: "Carbs",
  },
  {
    id: "ground-beef",
    name: "Ground Beef",
    emoji: "🥩",
    calories: 215,
    protein: 21,
    carbs: 0,
    fat: 14,
    servingSize: 100,
    servingUnit: "g",
    category: "Protein",
  },
  {
    id: "avocado",
    name: "Avocado",
    emoji: "🥑",
    calories: 240,
    protein: 3,
    carbs: 13,
    fat: 22,
    servingSize: 1,
    servingUnit: "avocado",
    category: "Fats",
  },
  {
    id: "apple",
    name: "Apple",
    emoji: "🍎",
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fat: 0.3,
    servingSize: 1,
    servingUnit: "medium",
    category: "Fruit",
  },
  {
    id: "whole-milk",
    name: "Whole Milk",
    emoji: "🥛",
    calories: 149,
    protein: 8,
    carbs: 12,
    fat: 8,
    servingSize: 1,
    servingUnit: "cup",
    category: "Dairy",
  },
  {
    id: "wheat-bread",
    name: "Wheat Bread",
    emoji: "🍞",
    calories: 69,
    protein: 3.6,
    carbs: 12,
    fat: 1.1,
    servingSize: 1,
    servingUnit: "slice",
    category: "Carbs",
  },
  {
    id: "peanut-butter",
    name: "Peanut Butter",
    emoji: "🥜",
    calories: 188,
    protein: 8,
    carbs: 6,
    fat: 16,
    servingSize: 2,
    servingUnit: "tbsp",
    category: "Fats",
  },
  {
    id: "tuna",
    name: "Tuna (canned)",
    emoji: "🐟",
    calories: 109,
    protein: 25,
    carbs: 0,
    fat: 1,
    servingSize: 100,
    servingUnit: "g",
    category: "Protein",
  },
  {
    id: "cottage-cheese",
    name: "Cottage Cheese",
    emoji: "🧀",
    calories: 206,
    protein: 25,
    carbs: 6,
    fat: 9,
    servingSize: 1,
    servingUnit: "cup",
    category: "Dairy",
  },
  {
    id: "lentils",
    name: "Lentils",
    emoji: "🫘",
    calories: 230,
    protein: 18,
    carbs: 40,
    fat: 0.8,
    servingSize: 1,
    servingUnit: "cup",
    category: "Protein",
  },
  {
    id: "spinach",
    name: "Spinach",
    emoji: "🥬",
    calories: 7,
    protein: 0.9,
    carbs: 1.1,
    fat: 0.1,
    servingSize: 1,
    servingUnit: "cup",
    category: "Vegetables",
  },
  {
    id: "orange",
    name: "Orange",
    emoji: "🍊",
    calories: 62,
    protein: 1.2,
    carbs: 15,
    fat: 0.2,
    servingSize: 1,
    servingUnit: "medium",
    category: "Fruit",
  },
  {
    id: "turkey-breast",
    name: "Turkey Breast",
    emoji: "🦃",
    calories: 135,
    protein: 30,
    carbs: 0,
    fat: 1,
    servingSize: 100,
    servingUnit: "g",
    category: "Protein",
  },
  {
    id: "quinoa",
    name: "Quinoa",
    emoji: "🌾",
    calories: 222,
    protein: 8,
    carbs: 39,
    fat: 3.5,
    servingSize: 1,
    servingUnit: "cup",
    category: "Carbs",
  },
  {
    id: "olive-oil",
    name: "Olive Oil",
    emoji: "🫒",
    calories: 119,
    protein: 0,
    carbs: 0,
    fat: 14,
    servingSize: 1,
    servingUnit: "tbsp",
    category: "Fats",
  },
];
